# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FoodTruck TrackR' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FoodTruck TrackR
  pod 'SwiftLint'
	
 # add pods for desired Firebase products
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
	

  target 'FoodTruck TrackRTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FoodTruck TrackRUITests' do
    # Pods for testing
  end

end
